import LegalDoc, { LegalHeading } from "@/components/legal-doc";

const CONTACT = "hello@muhaimin.dev";

export const metadata = {
  title: "Terms of Service — Repurpose AI"
};

export default function TermsPage() {
  return (
    <LegalDoc title="Terms of Service" updated="September 2026">
      <section>
        <LegalHeading>What this is</LegalHeading>
        <p>
          Repurpose AI (the &ldquo;service&rdquo;) takes audio/video recordings or YouTube links
          you give us and produces written drafts (LinkedIn posts, newsletter sections, short-form
          scripts) using third-party AI services. These terms are a plain-English summary of the
          deal between you and the maintainer of Repurpose AI. They are not legal advice.
        </p>
      </section>

      <section>
        <LegalHeading>Your content</LegalHeading>
        <p>
          You keep ownership of everything you upload. You promise that you have the right to use
          and process it — for example, that it is your own recording, or that you have permission
          to repurpose it. You may not upload anything that is illegal, infringes someone else&apos;s
          rights, or is intended to help someone else break the law.
        </p>
      </section>

      <section>
        <LegalHeading>AI output is a draft</LegalHeading>
        <p>
          Drafts are generated by machine models and may be wrong, misleading, or off-brand. Review
          and edit anything before you publish it. You are responsible for what you do with the
          output. Drafts and the underlying transcripts may be kept so you can view, re-edit, or
          regenerate them later.
        </p>
      </section>

      <section>
        <LegalHeading>Fair use & automated abuse</LegalHeading>
        <p>
          To keep costs down the service automatically enforces limits on file size, audio length,
          and how often you can start processing. Don&apos;t try to bypass these limits, and don&apos;t
          use the service to build competing products or as a free transcription API. Accounts that
          repeatedly abuse the service may be throttled or suspended without notice.
        </p>
      </section>

      <section>
        <LegalHeading>Liability</LegalHeading>
        <p>
          The service is provided &ldquo;as is&rdquo;. To the extent the law allows, the maintainer
          isn&apos;t liable for data loss, service interruptions, or anything you publish based on
          AI-generated drafts. If a law does not allow excluding these limits in your jurisdiction,
          they don&apos;t apply to you.
        </p>
      </section>

      <section>
        <LegalHeading>Takedowns & changes</LegalHeading>
        <p>
          If you see content on this service that shouldn&apos;t be here — for example something you
          own that was repurposed without permission — email us at{" "}
          <a className="font-medium text-primary-500 hover:underline" href={`mailto:${CONTACT}`}>
            {CONTACT}
          </a>{" "}
          and we&apos;ll review and remove it promptly. We may change these terms as the service
          evolves; changes take effect when posted.
        </p>
      </section>
    </LegalDoc>
  );
}