/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#1a1c1e",
        "surface": "#f9f9fc",
        "on-tertiary-fixed": "#002115",
        "secondary-fixed": "#d3e5f8",
        "tertiary-fixed-dim": "#7bd8b1",
        "secondary-fixed-dim": "#b7c8db",
        "on-surface-variant": "#444656",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dadadc",
        "surface-variant": "#e2e2e5",
        "on-secondary-fixed": "#0b1d2b",
        "on-tertiary-container": "#99f7cd",
        "tertiary-container": "#007454",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e2e2e5",
        "on-primary-container": "#dfe1ff",
        "surface-container-low": "#f3f3f6",
        "primary-fixed": "#dee0ff",
        "surface-container": "#eeeef0",
        "surface-tint": "#1e44f8",
        "error-container": "#ffdad6",
        "background": "#f9f9fc",
        "primary": "#0031dd",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#bbc3ff",
        "secondary": "#4f6070",
        "on-error-container": "#93000a",
        "secondary-container": "#d0e2f5",
        "on-primary-fixed-variant": "#002dcd",
        "inverse-on-surface": "#f0f0f3",
        "tertiary-fixed": "#97f5cc",
        "on-secondary-fixed-variant": "#384958",
        "primary-container": "#2a4dff",
        "surface-container-high": "#e8e8ea",
        "on-background": "#1a1c1e",
        "outline-variant": "#c4c5d9",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#00513a",
        "on-primary-fixed": "#000f5d",
        "surface-bright": "#f9f9fc",
        "tertiary": "#00593f",
        "primary-fixed-dim": "#bbc3ff",
        "on-secondary-container": "#536475",
        "outline": "#747688",
        "inverse-surface": "#2f3133",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-mobile": "0.75rem",
        "gutter": "1.25rem",
        "margin": "2rem",
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
      },
      fontFamily: {
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "display-xl": ["Space Grotesk", "sans-serif"],
        "display-2xl": ["Space Grotesk", "sans-serif"],
        "display-2xl-mobile": ["Space Grotesk", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "body-medium": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "caption-bold": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["17px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-medium": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "500" }],
        "caption-bold": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-xl": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-2xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-base": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "600" }],
        "display-2xl-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};